---
title: "Homework 6"
output: github_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
        echo = TRUE, 
        warning = FALSE,
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages
```{r}
library(broom)
library(modelr)
library(purrr)
```

# Problem 2

Importing and cleaning the data.
```{r warning = FALSE}
homicide_data = read.csv(file = "./data/homicide-data.csv") |> 
  janitor::clean_names() |> 
  mutate(
    city_state = paste(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    victim_age = ifelse(is.na(victim_age), NA_real_, victim_age)) |> 
  select(victim_race, victim_age, victim_sex, disposition, city_state) |> 
  filter(
    victim_race %in% c("White", "Black"),
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO,", "Tulsa, AL"))
```

Fitting the logistic regression model
```{r}
baltimore_data = homicide_data |> 
  filter(city_state == "Baltimore, MD")

baltimore_logistic = glm(
  disposition %in% c("Closed by arrest", "Closed without arrest") ~ victim_age + victim_sex + victim_race, family = binomial(), data = baltimore_data
)

summary(baltimore_logistic)

tidy_model = tidy(baltimore_logistic, conf.int = TRUE)
```

```{r}
sex_coef = tidy_model |> 
  filter(term == "sexMale")
```


```{r}
odds_ratio = exp(sex_coef$estimate)
confidence_upper = exp(sex_coef$conf.high)
confidence_lower = exp(sex_coef$conf.low)
```


```{r}
results = homicide_data |> 
  filter(victim_race %in% c("White", "Black")) |> 
  group_by(city_state) |> 
  nest() |> 
  mutate(
    model = map(data, ~ glm(disposition %in% c("Closed by arrest", "Closed without arrest") ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
    tidy_model = map(model, tidy, conf.int = TRUE)) |> 
  select(city_state, tidy_model)
```


```{r}
odds_ratios = results |> 
  unnest(tidy_model) |> 
  filter(term == "sexMale") |> 
  mutate(
    odds_ratio = exp(estimate),
    confidence_lower = exp(conf.low),
    confidence_upper = exp(conf.high)
  ) |> 
  select(city_state, odds_ratio, confidence_lower, confidence_upper)
```

```{r}
ggplot(odds_ratios, aes(x = odds_ratio, y = reorder(city_state, odds_ratio))) +
  geom_point(size = 3, color = "blue") +
  geom_errorbarh(aes(xmin = confidence_lower, xmax = confidence_upper), height = 0.2, color = "black") +
  labs(
    title = "Estimated Odds Ratios for Solving Homicides: Male vs. Female Victims",
    x = "Odds Ratio (OR)", 
    y = "City")
```


# Problem 3 

```{r}
birthweight_data = read.csv(file = "./data/birthweight.csv") |> 
  janitor::clean_names() |> 
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("Male", "Female")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9), labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
    malform = factor(malform, levels = c(0, 1), labels = c("Absent", "Present")),
    mrace = factor(mrace, levels = c(1, 2, 3, 4, 8), labels = c("White", "Black", "Asian", "Puerto Rican", "Other"))
  )
```

```{r}
missing_data = colSums(is.na(birthweight_data))
print(missing_data)
```

```{r}
birthweight_model = lm(
  bwt ~ blength + bhead + babysex + momage + ppbmi + smoken + wtgain + gaweeks + malform + fincome, 
  data = birthweight_data
)
```

```{r}
birthweight_data = birthweight_data |> 
  add_predictions(birthweight_model, var = "predicted_bwt") |> 
  add_residuals(birthweight_model, var = "residual_bwt")

```

```{r}
ggplot(birthweight_data, aes(x = predicted_bwt, y = bwt)) + 
  geom_point(alpha = 0.6) +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  labs(
    title = "Actual vs. Predicted Birthweight", 
    x = "Predicted Birthweight (grams)",
    y = "Actual Birthweight (grams)"
  )
```

```{r}
ggplot(birthweight_data, aes(x = predicted_bwt, y = residual_bwt)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(
    title = "Residuals vs. Predicted Birthweight",
    x = "Predicted Birthweight (grams)",
    y = "Residuals (grams)"
  )
```

```{r}
summary(birthweight_model)
```

```{r}
simplified_model = lm(
  bwt ~ blength + gaweeks, 
  data = birthweight_data
)

summary(simplified_model)
```

```{r}
interaction_model = lm(
  bwt ~ bhead * blength * babysex,
  data = birthweight_data
)

summary(interaction_model)
```


